[tools]
k3d = "latest"
kubectl = "latest"
node = "latest"
python = "3.14.2"
ruff = "latest"
uv = "latest"
neovim = "latest"
direnv = "latest"
sops = "3.11.0"

[env]
APP_REPO = 'pi-cluster'
GITOPS_REPO = 'pi-cluster-gitops'

[hooks]
enter = "bash ./scripts/setup_project"

[settings]
experimental = true

